"""Dataset/collate utilities for protein-conditioned PARNET experiments.

The canonical PARNET HFDS stores one RNA window with labels for all 223 tracks.
For a protein-conditioned model, the natural sample is instead one RNA window
paired with one specific RBP-cell track:

    (RNA window i, track j/protein j) -> eCLIP/control profile for track j

The Dataset below keeps samples close to the source data.  The collator performs
batch-level tensor work: one-hot encoding, sparse label extraction, padding masks,
and ProtT5 embedding lookup.
"""
from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

import torch
from torch.utils.data import Dataset
from mmpartnet.protein import ProteinConfig, ProteinSource, get_protein
import h5py

from mmpartnet.process.onehot import onehot


@dataclass(frozen=True)
class TrackProtein:
    track_index: int
    rbp_ct: str
    rbp: str
    cell: str
    h5_key: str
    embedding_dim: int
    match_type: str
    match_gene: str
    uniprot_acc: str


def load_track_protein_map(path: str | Path) -> list[TrackProtein]:
    """Load the TSV generated by scripts/build_prott5_track_map.py."""
    rows: list[TrackProtein] = []
    with Path(path).open(encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            if row["status"] != "matched":
                continue
            rows.append(
                TrackProtein(
                    track_index=int(row["track_index"]),
                    rbp_ct=row["rbp_ct"],
                    rbp=row["rbp"],
                    cell=row["ct"],
                    h5_key=row["h5_key"],
                    embedding_dim=int(row["embedding_dim"]),
                    match_type=row["match_type"],
                    match_gene=row["match_gene"],
                    uniprot_acc=row["uniprot_acc"],
                )
            )
    rows.sort(key=lambda x: x.track_index)
    return rows


def build_cell_vocab(track_map: Sequence[TrackProtein]) -> dict[str, int]:
    """Stable cell-line vocabulary for conditioning tensors."""
    return {cell: i for i, cell in enumerate(sorted({row.cell for row in track_map}))}


def sparse_track_to_dense(sparse: dict[str, Any], track_index: int, seq_len: int | None = None) -> torch.Tensor:
    """Extract one track from a sparse [n_tracks, L] label into a dense [L] vector."""
    size = sparse["size"]
    length = int(seq_len or size[1])
    dense = torch.zeros(length, dtype=torch.float32)
    values = sparse["values"]
    if len(values) == 0:
        return dense

    idx = torch.as_tensor(sparse["indices"], dtype=torch.long)
    vals = torch.as_tensor(values, dtype=torch.float32)
    keep = idx[0] == int(track_index)
    if not bool(keep.any()):
        return dense
    positions = idx[1, keep]
    valid = positions < length
    dense[positions[valid]] = vals[keep][valid]
    return dense


def pad_onehot(seq: str, target_len: int = 600) -> tuple[torch.Tensor, torch.Tensor]:
    """Return channels-first one-hot [4, target_len] and valid-position mask [target_len]."""
    seq = seq[:target_len]
    x = torch.zeros(4, target_len, dtype=torch.float32)
    if seq:
        oh = onehot(seq)
        x[:, : oh.shape[1]] = oh
    mask = torch.zeros(target_len, dtype=torch.bool)
    mask[: len(seq)] = True
    return x, mask


class ParnetMultimodalDataset(Dataset):
    """Flatten a PARNET split from windows into window-track samples.

    If the split has W windows and we use T tracks, then len(dataset) = W * T.
    ``dataset[k]`` maps to one window plus one RBP-cell track.
    """

    def __init__(
        self,
        hfds_split,
        track_map: Sequence[TrackProtein],
        *,
        binding_split=None,
        track_indices: Sequence[int] | None = None,
        max_windows: int | None = None,
        exact_length: int | None = None,
        max_length: int | None = None,
    ):
        self.hfds_split = hfds_split
        self.binding_split = binding_split
        self.track_map_by_index = {row.track_index: row for row in track_map}
        self.track_indices = list(track_indices) if track_indices is not None else [
            row.track_index for row in track_map
        ]
        missing = [i for i in self.track_indices if i not in self.track_map_by_index]
        if missing:
            raise ValueError(f"track indices missing from protein map: {missing[:10]}")

        limit = len(hfds_split) if max_windows is None else min(max_windows, len(hfds_split))
        self.window_indices: list[int] = []
        for i in range(limit):
            seq_len = len(hfds_split[i]["inputs"]["sequence"])
            if exact_length is not None and seq_len != exact_length:
                continue
            if max_length is not None and seq_len > max_length:
                continue
            self.window_indices.append(i)

    def __len__(self) -> int:
        return len(self.window_indices) * len(self.track_indices)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        window_offset = idx // len(self.track_indices)
        track_offset = idx % len(self.track_indices)
        window_index = self.window_indices[window_offset]
        track_index = self.track_indices[track_offset]
        sample = self.hfds_split[window_index]
        track = self.track_map_by_index[track_index]
        binding_label = None
        if self.binding_split is not None:
            binding = self.binding_split[window_index]["outputs"]["binding"]
            binding_label = float(binding[track_index])

        out = {
            "window_index": window_index,
            "window_name": sample.get("meta", {}).get("name", ""),
            "sequence": sample["inputs"]["sequence"],
            "track_index": track.track_index,
            "rbp_ct": track.rbp_ct,
            "rbp": track.rbp,
            "cell": track.cell,
            "protein_h5_key": track.h5_key,
            "protein_match_type": track.match_type,
            "protein_match_gene": track.match_gene,
            "protein_uniprot_acc": track.uniprot_acc,
            "eclip_sparse": sample["outputs"]["eCLIP"],
            "control_sparse": sample["outputs"]["control"],
        }
        if binding_label is not None:
            out["binding"] = binding_label
        return out


class MultimodalCollator:
    """Turn a list of multimodal samples into tensors for model input.

    Protein vectors are resolved through ``mmpartnet.protein`` so the FiLM
    workflow follows the repository's swappable protein-representation layer.
    ``protein_h5`` is kept as a convenience/default for the current ProtT5 H5
    provider.
    """

    def __init__(
        self,
        protein_h5: str | Path | None = None,
        seq_len: int = 600,
        cell_to_index: dict[str, int] | None = None,
        protein_source: ProteinSource | None = None,
        protein_rep: str = "prott5_h5",
        track_map: str | Path | None = None,
    ):
        self.protein_h5 = None if protein_h5 is None else Path(protein_h5)
        self.seq_len = seq_len
        self.cell_to_index = cell_to_index or {"HepG2": 0, "K562": 1}
        if protein_source is None:
            extra = {}
            if self.protein_h5 is not None:
                extra["h5_path"] = self.protein_h5
            if track_map is not None:
                extra["track_map"] = track_map
            protein_source = get_protein(protein_rep, ProteinConfig(mode=protein_rep, extra=extra))
        self.protein_source = protein_source

    def __getstate__(self):
        state = self.__dict__.copy()
        return state

    def _protein_vector(self, sample: dict[str, Any]) -> torch.Tensor:
        if hasattr(self.protein_source, "vector_by_key"):
            vec = self.protein_source.vector_by_key(str(sample["protein_h5_key"]))
        else:
            vec = self.protein_source.vector(sample["rbp"])
        if vec is None:
            raise KeyError(
                f"missing protein embedding for {sample['rbp']} "
                f"(h5_key={sample['protein_h5_key']})"
            )
        return torch.from_numpy(vec).float()

    def __call__(self, samples: Sequence[dict[str, Any]]) -> dict[str, Any]:
        onehots = []
        masks = []
        eclip = []
        control = []
        proteins = []
        binding = []

        for sample in samples:
            x, mask = pad_onehot(sample["sequence"], self.seq_len)
            onehots.append(x)
            masks.append(mask)
            eclip.append(sparse_track_to_dense(sample["eclip_sparse"], sample["track_index"], self.seq_len))
            control.append(sparse_track_to_dense(sample["control_sparse"], sample["track_index"], self.seq_len))
            proteins.append(self._protein_vector(sample))
            if "binding" in sample:
                binding.append(float(sample["binding"]))

        batch = {
            "onehot": torch.stack(onehots),
            "mask": torch.stack(masks),
            "protein_embedding": torch.stack(proteins),
            "eclip": torch.stack(eclip),
            "control": torch.stack(control),
            "track_index": torch.tensor([s["track_index"] for s in samples], dtype=torch.long),
            "cell_index": torch.tensor([self.cell_to_index[s["cell"]] for s in samples], dtype=torch.long),
            "window_index": torch.tensor([s["window_index"] for s in samples], dtype=torch.long),
            "rbp": [s["rbp"] for s in samples],
            "cell": [s["cell"] for s in samples],
            "rbp_ct": [s["rbp_ct"] for s in samples],
            "window_name": [s["window_name"] for s in samples],
            "protein_h5_key": [s["protein_h5_key"] for s in samples],
        }
        if binding:
            batch["binding"] = torch.tensor(binding, dtype=torch.float32)
        return batch
